# Generated by Django 5.2.4 on 2025-07-27 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chats', '0002_alter_user_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('guest', 'Guest'), ('member', 'Member'), ('host', 'Host'), ('admin', 'Admin')], default='guest', max_length=10),
        ),
    ]
