# Generated by Django 5.2.4 on 2025-07-20 22:22

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chats', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='password',
            field=models.CharField(help_text='Password must be at least 8 characters long', max_length=128, validators=[django.core.validators.MinLengthValidator(8)]),
        ),
    ]
